spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/codecollab
spring.datasource.username=postgres
spring.datasource.password=Akshay@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


